#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#autostart
$HOME/.config/polybar/launch.sh
feh --bg-scale $HOME/Downloads/paper2.jpg
pgrep -x compton > /dev/null || compton &
pgrep -x nm-applet > /dev/null || nm-applet &
sleep 1
pgrep -x sxhkd > /dev/null || sxhkd &
